version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: myfitnessbro
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
